version: "3"
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "devonfw"
      ACCEPT_EULA: "Y"
    ports:
      - 1431:1431
      - 1433:1433
      - 1434:1434